### ISSUE TITLE
Be specific about transitioning CSS properties

### ISSUE THREAD

**Issue by oliverjam** [joe-dev-public/fac-agency-website#72]
https://github.com/joe-dev-public/fac-agency-website/blob/0382c79b74a10b89a73c3770ffe593f3a2042547/style.css#L92

If you don't specify a CSS property to transition it'll default to `all`. This can be quite dangerous, as things you wouldn't expect to transition end up doing wacky stuff.

In this case if I refresh the page in mobile view I sometimes see the hamburger menu's background SVG pattern fly across the screen and disappear at the top. I _think_ this is because the image loads in after everything else, then realises it has to be up the top and `scale(0)`. Since _everything_ is being transitioned the position also animates and it ends up flying around rather than just appearing invisible from the start.

I would always try and choose the exact property I want to transition, e.g.

```css
.thing {
  transition: transform 0.25s ease-in-out;
}
```

If you need multiple properties to transition you can duplicate the whole definition like this:

```css
.thing {
  transition: transform 0.25s ease-in-out, color 0.1s ease-in;
}
```
